config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('jwitter.urls')),
    path('admin/', admin.site.urls),
]

jwitter/urls.py
from django.urls import path
from .views import dashboard, profile_list, profile

app_name= 'jwitter'


urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('profile-list/', profile_list, name='profile_list'),
    path('profile/<int:pk>', profile, name='profile'),
]

jwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        'self',
        related_name = 'followed_by',
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()

class Jweet(models.Model):
    user = models.ForeignKey(
        User,
        related_name ="Jweets", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return(
            f"{self.user}"
            f"({self.created_at:%y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

jwitter/forms.py
from django import forms
from .models import Jweet


class JweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder":"Jweet somethings...",
                "class":"textarea is-success is-medium",
            }
        ),
        label="", 
    )


    class Meta:
        model = Jweet
        exclude = ('user', )

jwitter/views.py
from django.shortcuts import render, redirect
from .forms import JweetForm
from .models import Profile, Jweet

def dashboard(request):
    form = JweetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            jweet = form.save(commit=False)
            jweet.user = request.user
            jweet.save()
            return redirect("jwitter:dashboard")

    followed_jweets = Jweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")
    context = {
        'form': form,
        'jweets': followed_jweets,
    }
    return  render(request, 'jwitter/dashboard.html', context)


def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    context = {
        'profiles':profiles,

    }
    return render(request, 'jwitter/profile_list.html', context)


def profile(request, pk):
    # check user exists
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == 'POST':
        present_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            present_user_profile.follows.add(profile)
        elif action == "unfollow":
            present_user_profile.follows.remove(profile)
        present_user_profile.save()
    context = {
        'profile':profile,
    }
    return render(request, 'jwitter/profile.html', context)

templates/_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>{% block title %}Jwitter{% endblock %}</title>
  </head>
  <body>

<!-- header -->
<a href="{% url 'jwitter:dashboard' %}">
  <section class="hero is-small is-primary mb-4">
    <div class="hero-body">
      <h1 class="title is-1">social network</h1>
      <p class="subtitle is-4">Welcome to Jwitter</p>
    </div>
  </section>
</a>
    <div class="container">
      <div class="columns">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/jwitter/dashboard.html
{% extends '_base.html' %}


{% block content %}
  <div class="column">
    {% for jweet in jweets %}
      <div class="box">
        {{jweet.body}}
        <span class="is-small has-text-grey-light">
          ({{jweet.created_at}} by {{jweet.user.username}})
        </span>
      </div>
      {% endfor %}
  </div>

<div class="column is-one-third">
    <!-- button  profile_list-->
    <div class="block">
        <a href="{% url 'jwitter:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>
    <!-- button profile -->
    <div class="block">
        <a href="{% url 'jwitter:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>



    <!-- Form JweetForm -->
  <div class="block">
    <div class="block">
      <h2 class="title is-2">Add a Jweet</h2>
    </div>
    <div class="block">
      <form class="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button is-success is-fullwidth is-medium mt-5"
          type="type">Jweet</button>

      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/jwitter/profile.html
{% extends '_base.html' %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Jweets
    </h1>
    </div>
    <form class=""  method="post">
      {% csrf_token %}
      <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
        <button class="button is-success is-static">Follow</button>
        <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
        {% else %}
        <button class="button is-success" name="follow" value="follow">Follow</button>
        <button class="button is-danger is-static">Unfollow</button>
        {% endif %}
      </div>
    </form>
    
    <div class="content">
      {% for jweet in profile.user.Jweets.all %}
        <div class="box">
          {{jweet.body}}
          <span class="is-small has-text-grey-light">
            {{jweet.created_at}}
          </span>
        </div>
        {% endfor %}
    </div>


</div>







<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'jwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'jwitter:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'jwitter:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>



</div>

{% endblock content %}

templates/jwitter/profile_list.html
{% extends '_base.html' %}


{% block content %}
  <div class="">
    {% for profile in profiles %}
      <div class="blck">
        <div class="card">
          <a href="{% url 'jwitter:profile' profile.id %}">
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png"
                     alt="Placeholder image">
                  </figure>
                </div>
                <div class="media-content">
                  <p class="title is-4">
                    {{profile.user.username}}
                  </p>
                  <p class="subtitle is-6">
                    @{{profile.user.username|lower}}
                  </p>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}